### ISSUE TITLE
Привести инспеции рубокопа в порядок, добавить его запуск в ci

### ISSUE THREAD

**Issue by kovalevsky** [IT61/it61-rails#115]
Я понимаю, что уже подключен сервис для комплексного анализа кода проекта с линтерами для файлов стилей, маркапа и руби. Но для руби он работает как-то не очень.
В случае с руби, вот прямо сейчас запуск рубокопа говорит, что:
`157 files inspected, 53 offenses detected`

Предлагаю сделать так, чтобы рубокоп был доволен, в идеале научить бота-стиле-комментатора понимать политики рубокопа. Если это не получится, то добавить запуск рубокопа отдельным стейджем в ci.

Кроме того, бот-комментатор это хорошо, но если pr не соответствует принятым стандартам оформления кода, то ci не должен быть зеленым.

**Comment by Vitallium** [comment]
HoundCI работает только для измененные файлы в PR. Поэтому он не детектит другие файлы.

>Кроме того, бот-комментатор это хорошо, но если pr не соответствует принятым стандартам оформления кода, то ci не должен быть зеленым.
Поддерживаю.

**Comment by vitallium** [comment]
Просто берем и используем [standardrb](https://github.com/testdouble/standard) :)
