### ISSUE TITLE
Сервер отдает 500 код на запрос аватарки

### ISSUE THREAD

**Issue by LibertyPaul** [IT61/it61-rails#125]
Вот так моя аватарка выглядит в списке участников:
![image](https://cloud.githubusercontent.com/assets/2873698/22398858/3f4e6aca-e5a1-11e6-9253-c92c7867889b.png)

На запрос jpeg файла сервер отдает 500 код:
![image](https://cloud.githubusercontent.com/assets/2873698/22398884/cde87384-e5a1-11e6-8368-8557f809a35a.png)

**Comment by Vitallium** [comment]
Поправил. Имя файла потерялось при миграции.
