### ISSUE TITLE
Проблема при регистрации через OAuth с помощью Google

### ISSUE THREAD

**Issue by alx-khramov** [IT61/it61-rails#129]
Steps to reproduce:
Регистрирую нового пользователя, использую Google.
Из Google подставляются поля имени, фамилии, адреса почты (alx.khramov@gmail.com).
Меняю имя и фамилию на написанные на кириллице (от гугла пришла латиница).
Заполняю телефон, больше ничего.
Жму "Все верно", происходит редирект на https://it61.info/users/1584. Появляется красное flash сообщение об ошибке, ничего конкретного. При попытке "сохранить" данные на этой странице flash сообщение повторяется снова.
Поле телефона отображается неправильно. (см. скриншот). В DOM у обертки поля телефона присутствует класс field_with_errors. Возможно не поддерживается формат телефона с восьмерки.
![image](https://cloud.githubusercontent.com/assets/1245209/22799855/4fd1d5e6-ef18-11e6-8222-ad0d80d5c5de.png)
К сожалению у самого нет сейчас времени прислать PR, поэтому пока оставляю issue.

**Comment by alx-khramov** [comment]
Да, телефон с +7 вместо восьмерки нормально сохраняется и не вызывает ошибок.

**Comment by kovalevsky** [comment]
Эта проблема не имеет непосредственного отношения к oauth, поэтому описал ее в отдельной задаче: https://github.com/IT61/it61-rails/issues/139
