### ISSUE TITLE
Не работает привязка по соц. сети.

### ISSUE THREAD

**Issue by NeverHappened** [IT61/it61-rails#148]
Нажимаю на гугл - запрос проходит, но гугл не добавляется к списку подключенных соц. сетей

**Comment by Photon79** [comment]
Добавлю..  Не только гугл..  Любая соц.сеть, кроме той, через которую изначально регистрировался

**Comment by Vitallium** [comment]
Fixed in master. See https://github.com/IT61/it61-rails/commit/83435cf50f419a6e5ef2d64a733d1e24ade0b123
