### ISSUE TITLE
Формировать мета-теги для events#show

### ISSUE THREAD

**Issue by kovalevsky** [IT61/it61-rails#149]
Сейчас при расшаривании страницы мероприятия в соц. сети или при отправки ссылки в мессенжер отображается вот такая не очень полезная информация:
![telegram 2017-02-28 12-25-39](https://cloud.githubusercontent.com/assets/203871/23399528/95d40a9e-fdb1-11e6-95a3-8b920daa386b.png)

В проекте уже подключен джем meta-tags. С его помощью нужно формировать содержание meta description, og-тегов и img_src.

Критично для страницы события, полезно и для остальных страниц.

**Comment by vitallium** [comment]
Landed in https://github.com/IT61/it61-rails/commit/225ddaa30974169273f856980b07f92a1fb7de07
