### ISSUE TITLE
Скрывать блок контента в аккордеоне при пустом контенте

### ISSUE THREAD

**Issue by lex111** [IT61/it61-rails#156]
Если нет контента в блоке:
![image](https://cloud.githubusercontent.com/assets/4408379/23921445/b88e3a78-090f-11e7-8ca4-33f240277d2f.png)

То не раскрывать его по умолчанию и убрать иконку раскрытия:
![image](https://cloud.githubusercontent.com/assets/4408379/23921483/db245db0-090f-11e7-87f6-446068073874.png)

**Comment by Vitallium** [comment]
Пофиксил в мастере.
