### ISSUE TITLE
Не показываются фотографии из Instagram

### ISSUE THREAD

**Issue by lex111** [IT61/it61-rails#158]
Сейчас при переходе на страницу "Фотографии", фотографии не отображаются, возможно временное явление (вчера показывались), но может стоит, в подобных случаях выводить какое-нибудь сообщение о том, что фотографии не удалось загрузить?
![image](https://cloud.githubusercontent.com/assets/4408379/24082698/e7f17e14-0cda-11e7-94c2-51e7fb48bcdc.png)

**Comment by Vitallium** [comment]
Ссаный инстаграм закрыл доступ для просмотра фоток по тегу: `https://www.instagram.com/explore/tags/it61`

**Comment by lex111** [comment]
Кстати, да, заметил это несколько дней назад, что перестали открываться ссылки на хештеги в десктопной версии (молодцы конечно, при этом ссылки также остались кликабельными, что странно), но не предполагал, что и API это тоже коснется (по идее разные вещи), непонятно зачем они так сделали?

**Comment by Vitallium** [comment]
Без понятия. Я пока временно скрыл этот пункт меню. Спасибо за информацию! :-)

**Comment by lex111** [comment]
Аа, не увидел сразу, что вы парсите с этой веб-страницы фотографии, а почему не использовать API для этой цели или нет такой возможности?

**Comment by Vitallium** [comment]
API тоже не предоставляет простого способа отображать фотки. Там нужен аккаунт и авторизация через браузер (но тут не уверен)

**Comment by lex111** [comment]
Судя по [этой инструкции](https://github.com/adrianengine/jquery-spectragram/wiki/How-to-get-Instagram-API-access-token-and-fix-your-broken-feed), нужно получить API-токен только один раз (предварительно зарегистрировать приложение), т.е. OAuth-авторизация не нужна. Причем по указанной выше инструкции для получения токена нужен запущенный локальный веб-сервер, а есть [сервис](https://elfsight.com/service/generate-instagram-access-token/), который позволяет сгенерировать токен без этого. И напоследок, [ссылка на документацию для хештегов](https://www.instagram.com/developer/endpoints/tags/).

**Comment by lex111** [comment]
О, починили, ссылка https://www.instagram.com/explore/tags/it61 снова работает, может откроем пункт меню c фотографиями :smile:?

**Comment by Vitallium** [comment]
Fixed
