### ISSUE TITLE
Сохранение отредактированного мероприятия

### ISSUE THREAD

**Issue by alx-khramov** [IT61/it61-rails#170]
1. Открыть форму редактирования мероприятия, например: https://it61.info/events/2017-06-24-rnd-js-3-170/edit
2. Изменить данные в полях формы
3. Нажать "Сохранить"
Нажатие кнопки сабмитит форму, но пользователь не получает об этом никакого оповещения, страница даже не обновляется.
MacOS, Chrome 58

**Comment by Vitallium** [comment]
Fixed in master
