### ISSUE TITLE
Сделать так, чтобы на индексной странице мероприятий было понятно, во сколько начинается мероприятие

### ISSUE THREAD

**Issue by rainrb** [IT61/it61-rails#24]
Предлагаю выделить дату и время начала мероприятия большим, красным, жирным, нетерпеливо-мигающим шрифтом.

Если кто-то лучше меня разбирается в дизайне - можно предложить какое-либо другое решение:) Основная идея сделать так, чтобы дата и время начала стали заметными.

**Comment by kovalevsky** [comment]
Исправлено в pr: https://github.com/IT61/it61-rails/pull/40
