### ISSUE TITLE
ics-файлы для мероприятий

### ISSUE THREAD

**Issue by igoralekseev** [IT61/it61-rails#44]
Хотелось бы иметь возможность добавить мероприятие себе в календарь. 
Нужна ссылку на мероприятие в формате ics (или любом другом сопоставимом)

**Comment by kovalevsky** [comment]
Так есть же гуглкалендарь со всеми мероприятиями: https://www.google.com/calendar/ical/bdod7ds9v0m4hsvmbcrmvrjbjo%40group.calendar.google.com/public/basic.ics

**Comment by kovalevsky** [comment]
@igoralekseev  так есть же гуглкалендарь со всеми мероприятиями: https://www.google.com/calendar/ical/bdod7ds9v0m4hsvmbcrmvrjbjo%40group.calendar.google.com/public/basic.ics

**Comment by igoralekseev** [comment]
он не совсеми, а с какими-то странными :) Ох если я накоммичу-пуллреквестю, держитесь!

**Comment by igoralekseev** [comment]
Кстати в it52 все норм -- https://github.com/NNRUG/it52-rails/commit/ea535c1cc32157e89f60f8fae71366d716a1641f

Ссылка на ics файл для каждого события

**Comment by kovalevsky** [comment]
В нашем календаре те события, для которых нажали на кнопку "опубликовать в гуглкалендарь".
Если там нет каких-то событий, то это на совести контент-менеджера.

Нужна ссылка на каждое мероприятие? Мне сложно судить, я не пользуюсь гуглкалендарем и хз как открывать эти ссылки.

**Comment by igoralekseev** [comment]
ics файлы открывает на Маке стандартный календарь, так что ивенты попадают и в notification center и в телефон и везде. И телефон жужжит, а вот если принял приглашение в ВК или FB то телефон не жужжит и можно все проспать.

**Comment by rainrb** [comment]
А с календарем какие проблемы? Я вроде бы посмотрел -- все опубликованные мероприятия отображаются. Единственный неприятный момент -- пропала ссылка на календарь (вроде бы раньше была в профиле пользователя).

Давайте может быть я добавлю ОГРОМНУЮ плашку вверху страницы со ссылкой на гуглокалендарь?

**Comment by rainrb** [comment]
Такая задача, оказывается есть https://github.com/IT61/it61-rails/issues/48

**Comment by kovalevsky** [comment]
@rainrb это не совсем такая задача (к тому же я ее добавил позднее).
В этой задаче речь об отдельной ссылке на каждое мероприятие. В той – календарь с событиями, для которых нажали кнопку "опубликовать в календаре".

**Comment by kovalevsky** [comment]
> он не совсеми, а с какими-то странными :)

@igoralekseev можешь пояснить, что именно в общем календаре кажется странным или не соответсвует ленте на сайте?

**Comment by igoralekseev** [comment]
Ну во-первых там много событий но не все -- я сначала подумал только на текущий месяц, как оказалось это которые нажали кнопку "опубликовать в календаре".

Я вот как бы (юз кейз) хочу прийти на митап и я не знаю опубликовано ли это мероприятие в календаре или нет. В большинстви случаев я узнаю о событии в соц сетях и был бы рад видеть ссылку на ics уже там, в постах в соц сети или хотя бы здесь на сайте

**Comment by rainrb** [comment]
Добавил возможность скачивать ics-файлы мероприятий.
![img](https://api.monosnap.com/rpc/file/download?id=BWkrgv8bU7TS0FojD61lyr3tFqO78s)

@igoralekseev, посмотри пожалуйста соответствует ли реализация ожиданиям.

**Comment by rainrb** [comment]
Фидбэка нет, считаем что все ок. Если проблемы возникнут -- переоткроем задачу.

**Comment by igoralekseev** [comment]
Да все супер, спасибо!
