### ISSUE TITLE
Восстановление пароля

### ISSUE THREAD

**Issue by kovalevsky** [IT61/it61-rails#46]
Сейчас не реализован механизм для восстановления пароля.
Нужно его реализовать, добавить ссылку для восстановления пароля на страницу логина.

Описание того, как этот делается тут: https://github.com/NoamB/sorcery/wiki/Reset-password

Отдельно нужно убедиться, что механизм смены пароля работает корректно в случае, если пользователь был зарегистрирован через соц. сеть и мы знаем его email.

Задача подразумевает:
– миграции,
– контроллерную логику,
– мейлер и вьюхи,
– тесты.

**Comment by RuZniki** [comment]
Я пароль забыл.

**Comment by pplevako** [comment]
Я взял эту задачу.

**Comment by kovalevsky** [comment]
@pplevako укажи плс себя в assignee.

**Comment by pplevako** [comment]
@kovalevsky не могу, видимо недостаточно прав. Назначишь/добавишь пожалуйста?

**Comment by kovalevsky** [comment]
Конечно, готово.
