### ISSUE TITLE
Дефекты верстки блоков с именем пользователя

### ISSUE THREAD

**Issue by kovalevsky** [IT61/it61-rails#49]
Блок с именем залогиненного пользователя отображается некорректно для устройств всех размеров за исключением extra small.

 
Нужно обеспечить вертикальное выравнивание аватара и имени пользователя.
Пример 1:
![it 2015-02-01 14-24-51](https://cloud.githubusercontent.com/assets/203871/5991909/a3d1732c-aa1e-11e4-8d08-e0ab2272d58b.jpg)

Пример 2:
![it 2015-02-01 14-18-54](https://cloud.githubusercontent.com/assets/203871/5991910/a9bb8412-aa1e-11e4-8e6c-d557aa5362cf.jpg)

В навбаре аватар должен отображаться слева от имени пользователя, вне зависимости от количества строк, которые занимает имя пользователя.

Пример 1:
![it 2015-02-01 14-20-54](https://cloud.githubusercontent.com/assets/203871/5991911/afa6c3aa-aa1e-11e4-94d1-7246ba7c2774.jpg)

Пример 2:
![it 2015-02-01 14-22-33](https://cloud.githubusercontent.com/assets/203871/5991912/b697652a-aa1e-11e4-8f73-bb48a48429a9.jpg)

**Comment by rainrb** [comment]
Вроде бы ничего не воспроизводится из вышеперечисленного.
