### ISSUE TITLE
Разделить ленту на прошедшие и будущие мероприятия

### ISSUE THREAD

**Issue by kovalevsky** [IT61/it61-rails#51]
Страница со список мероприятий уже достаточно большая. Стоит добавить разделение на будущие и прошедшие мероприятия.

Например, в виде "переключателя" «Будущие»/«Прошедшие».
Роутинг:
будущие – /events
прошедшие – /events/archive.

К обсуждению: нужно ли разделять RSS на два фида или оставить, как сейчас?

**Comment by Nu-hin** [comment]
Считаю, что разделять не нужно. Фида должна агрегировать все события.

**Comment by kovalevsky** [comment]
Поступило предложение не делать два таба, но добавить в ленту визуальный разделитель в таком духе:
![img_2066](https://cloud.githubusercontent.com/assets/203871/6000201/35dc11f0-aaec-11e4-8f05-a8b54ee43b7c.JPG)

**Comment by rainrb** [comment]
Имхо не самая актуальная задача, ну и я с @Nu-hin согласен. Я бы закрыл этот таск.

**Comment by Nu-hin** [comment]
Сделана первая реализация. Пока закрою.
