### ISSUE TITLE
Пейджинг мероприятий

### ISSUE THREAD

**Issue by kovalevsky** [IT61/it61-rails#52]
Сначала сделать #51.

На одной странице нужно отображать 10 мероприятий.
Если мероприятий больше, то показывать кнопку "Показать еще 10" (если осталось меньше 10, то отображать количество мероприятий, которые еще не показаны).
При клике в кнопку загружать мероприятия и добавлять их в ленту без перезагрузки страницы.

**Comment by Nu-hin** [comment]
Может быть лучше infinite scroll?

**Comment by kovalevsky** [comment]
Можно и infinite scroll, но лично мне больше нравится подгружать контент вручную.

**Comment by Nu-hin** [comment]
Ну так а что делать-то будем?

Давай начнем с кнопки, потом прикрутим скролл, если захочется.

**Comment by Nu-hin** [comment]
В коммите ce383211ad06c1655b794af28722eb1e4b499617.
