### ISSUE TITLE
После переноса слетели авторизации VK, FB

### ISSUE THREAD

**Issue by Jugastrov** [IT61/it61-rails#53]
VK:
https://oauth.vk.com/authorize?client_id=4373282&display=&redirect_uri=http%3A%2F%2Fit61.info%2Foauth%2Fcallback%3Fprovider%3Dvk&response_type=code&scope=&state=

Ответ: {"error":"invalid_request","error_description":"redirect_uri has wrong domain, check application settings"}

FB:
https://graph.facebook.com/oauth/authorize?client_id=630693630357188&display=page&redirect_uri=http%3A%2F%2Fit61.info%2Foauth%2Fcallback%3Fprovider%3Dfacebook&response_type=code&scope=email%2Cpublish_stream&state=

Ответ: {
   "error": {
      "message": "Invalid redirect_uri: URL  \u043d\u0435 \u0441\u043e\u043e\u0442\u0432\u0435\u0442\u0441\u0442\u0432\u0443\u0435\u0442 \u043d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0430\u043c \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u044f",
      "type": "OAuthException",
      "code": 191
   }
}

**Comment by rainrb** [comment]
Вроде бы проблема решена.
