### ISSUE TITLE
Сделать место проведения мероприятия ссылкой на яндекс-карту

### ISSUE THREAD

**Issue by rainrb** [IT61/it61-rails#56]

**Comment by Nu-hin** [comment]
Как ты себе это представляешь? Просто передавать указанное место в качества поискового запроса к ЯК? Типа, например "Рабочее пространство "Mesto", Максима Горького ул. 151"?

**Comment by rainrb** [comment]
В первом приближении да, если работать не будет можно будет подумать об альтернативных вариантах

**Comment by kovalevsky** [comment]
Вроде должно нормально работать все, яндекс найдет.
