### ISSUE TITLE
Количество участников мероприятия

### ISSUE THREAD

**Issue by Jugastrov** [IT61/it61-rails#59]
Хотелось бы в данном случае выводить хотябы 4 полных ряда аватарок
http://joxi.ru/v29N75YhqMkzAG

**Comment by thesunwave** [comment]
Может сделать слайдер и показывать всех?

**Comment by rainrb** [comment]
@thesunwave можно и слайдер. Вообще дизайн сайта это вопрос открытый, хорошо бы его привести в порядок.

**Comment by kovalevsky** [comment]
> Хотелось бы в данном случае выводить хотябы 4 полных ряда аватарок
http://joxi.ru/v29N75YhqMkzAG
А каким образом предлагаешь этого добиться?
Делать блок динамической ширины? Как-то хитро лейаутить аватары внутри контейнера с фиксированной шириной так, чтобы получались полностью заполненные строки и отступы слева-справа?
Задача вообще актуальна?)
