### ISSUE TITLE
Авторизация/регистрация (UX feedback) 

### ISSUE THREAD

**Issue by Jugastrov** [IT61/it61-rails#61]
![it61 - slack](https://cloud.githubusercontent.com/assets/1388985/10635197/9fdca87c-77ff-11e5-9f1c-183a15407cf8.jpg)

**Comment by kovalevsky** [comment]
Нужна конкретика, какие именно сообщения имеются ввиду? Причем тут мыло "или вообще не регистрировался"?

Лучше составлять более конкретные задачи, чтобы можно было взять и сделать, без дополнительных обсуждений и расследований.
