### ISSUE TITLE
Cookies lifetime

### ISSUE THREAD

**Issue by LibertyPaul** [IT61/it61-rails#62]
Предлагаю установить время жизни для кукисов хотя бы в пару недель, чтобы не приходилось логиниться при каждом входе.

**Comment by kovalevsky** [comment]
Реализовано 235ea6db6b0407372b9537034e293504127f88c7

**Comment by LibertyPaul** [comment]
Тогда вам надо пометить это как баг, потому что я только что:
0. Зашел на http://it61.info/events
1. Залогинился(через GitHub)
2. Закрыл браузер
3. Открыл браузер
4. Снова зашел на http://it61.info/events
5. Увидел предложение залогиниться или зарегистрироваться

**Comment by kovalevsky** [comment]
Задеплоено только сегодня. Возможно, не стоило закрывать задачу до деплоймента.

**Comment by LibertyPaul** [comment]
Проверил.
Все осталось по прежнему.

Может стоит открыть 'issue', до тех пор, пока она не будет решена?

**Comment by kovalevsky** [comment]
Вообще, описанный выше кейс не похож на проблему срока жизни сессии.
В каком броузере воспроизводится проблема?
Если воспроизводится еще у кого-то из пользователей, то задачу стоит открыть.

**Comment by LibertyPaul** [comment]
Opera 33.0.1990.58
Хм, в Firefox все нормально работает.

**Comment by LibertyPaul** [comment]
На Chrome 46.0.2490.80 (64-bit) проблема воспроизводится.

Проверил под Win10 на Opera проблема воспроизводится.
