### ISSUE TITLE
Верстка страницы одного мероприятия

### ISSUE THREAD

**Issue by vtambourine** [IT61/it61-rails#70]
Страница с подробным описанием одного мероприятия, ссылками на участие, редактирование, создание события в календаре, списком участников и нормально размеченным описанием.

Макет 8: http://ninjamock.com/s/W538T

**Comment by vpetrenko** [comment]
Набросал основной скелет страниц списка мероприятий и страницу мероприятия. Нужна помощь по допиливанию адаптивки и мелочей в оформлении.
