### ISSUE TITLE
Быстрая регистрация в Слаке с главной страницы

### ISSUE THREAD

**Issue by vtambourine** [IT61/it61-rails#72]
Кнопка "Присоединиться" на главной странице должна запрашивать только почту пользователя, сразу же присылая инвайт в Слак. Создание аккаунта на сайте следует протягивает через письмо-напоминалку.

**Comment by Jugastrov** [comment]
Если нужна быстрая регистрация, то главная должна выглядеть так http://joxi.ru/D2P86MnsMKV723

**Comment by kovalevsky** [comment]
В Slack API нет задокументированных методов для программной отправки приглашений в команду. Из готоывх реализаций гуглится только вот такой не самый прямой способ: https://levels.io/slack-typeform-auto-invite-sign-ups и плагины для drupal и еще чего-то.
Скорее всего, с ивайтами придется повозиться.

Если все же делать:
Для хранения данных об отправленных приглашения нужно сделать модель, например, SlackInvites с аттрибутами:
* email,
* количество отправленных инвайтов.

При обработке сабмита формы нужно делать `SlackInvite.find_or_create`.

**Comment by kovalevsky** [comment]
Сейчас у нас используется вот такая реализация отправки инвайтов: https://github.com/rauchg/slackin. Возможно получится использовать JS API, который есть в этой реализации. Это может быть быстро в плане разработки, но не слишком хорошо в плане безопасности.
