### ISSUE TITLE
Docker для dev-окружения

### ISSUE THREAD

**Issue by kovalevsky** [IT61/it61-rails#76]
Для упрощения подключения к разработке имеет смысл подготовить докер-обвязку для dev-окружения.
В том числе образ pg, с корректно развернутой базой для стейджинга. Репозитории (кроме БД) можно использовать из https://github.com/httplab

**Comment by tamtamchik** [comment]
Resolved in #103

**Comment by tamtamchik** [comment]
Closed in #103
