### ISSUE TITLE
Раздел Компании – отправка писем о запросах и участниках

### ISSUE THREAD

**Issue by kovalevsky** [IT61/it61-rails#82]
Две категории получателей: администраторы и пользователи.

Письма администраторам:
- новая заявка на членство в компании;
- добавлен новый пользователь;
- удален пользователь;
- ~~изменены права пользователя~~ [не делаем, пока нет контроллерной логики].

Письма пользователям:
- запрос отправлен;
- запрос подтвержден, пользователь добавлен в компанию;
- пользователь удален из компании.

**Comment by valexl** [comment]
@kovalevsky эта задача актуальна? Могу ее забрать? И сразу пустой layout создать для писем

**Comment by kovalevsky** [comment]
@valexl Да, вполне актуальна, забирай!

**Comment by valexl** [comment]
@kovalevsky, назначь пожалуйста на меня. чтоб видно было что занята..

**Comment by kovalevsky** [comment]
@valexl вступи плс в организацию it61 :)

**Comment by valexl** [comment]
@kovalevsky я ж правильно понимаю что сейчас из всех пунктов уведомлений для админа, возможно, только отсылать для ситуаций: "Добавлен новый пользователь", "Удален пользователь"? 

А для пользователя только "Пользователь удален из компании" и "Запрос подтвержден, пользователь добавлен в компанию"(заявка автоматически одобряется в CompanyMembersController#create и можно сразу отправлять уведомление что запрос подтверждён)

**Comment by kovalevsky** [comment]
@valexl А в чем проблема с остальными событиями? 
Сейчас заявки создаются, значит отправить письмо по событию "новая заявка на членство в компании" возможно.
Роли сейчас есть, но нет контроллерной логики для их редактирования, поэтому отправку письма об изменения прав делать пока не нужно.

Отправку письма пользователю о том, что он оставил заявку сделать тоже ничего не мешает.

> (заявка автоматически одобряется в CompanyMembersController#create и можно сразу отправлять уведомление что запрос подтверждён). 

Подтверждение заявки логично делать в MembershipRequestsController. В параллельном бранче это уже реализовано но сейчас не принципиально в каком контроллере разместить этот код. При мерже бранчей это нужно будет исправить и перенести куда следует

**Comment by valexl** [comment]
@kovalevsky ну так просто нет MembershipRequestsController это и смущает. Может быть забыл какой нибудь PR в master залить?

**Comment by kovalevsky** [comment]
oops
Извини, я не написал в таске, что нужно делать бранч под эту задачу от company2, а не от мастера. Много уже кода написано?

**Comment by valexl** [comment]
@kovalevsky ну так.. Все шаблоны, layout, тесты и успел сделать отправку админу о новом пользователе и удалении. Не думаю что будут большие проблемы для merge. 


PR тогда получается тоже в company2 делать?

**Comment by valexl** [comment]
И кстати что юзать для отправки? Sidekiq/Resque/Delayed_job ?

**Comment by kovalevsky** [comment]
@valexl Я тоже не думаю что будут серьезные конфликты.
Да, идея в том, чтобы довести организации до какой-то работоспособной версии и только потом вмержить их в мастер.

**Comment by kovalevsky** [comment]
Сейчас отправка почты происходит синхронно. Это, конечно, не очень хорошо.
Если есть желание сразу сделать воркеры, то я предлагаю использовать ActiveJob + Sidekiq (https://github.com/mperham/sidekiq/wiki/Active-Job).
Resque/DJ уж слишком олдскулл.

**Comment by valexl** [comment]
У каждого просто свои наработки для deploy. Поэтому решил уточнить. Ок. Тогда сделаю сразу с воркерами.

**Comment by valexl** [comment]
@kovalevsky а что осталось в задаче по компаниям? Потому что я уперся немного в процесс добавления и удаления пользователя в компанию.. Пытаюсь тестами разрулить но они не работают.. И я хз это тесты кривые или реально ошибка.. Проверить не удается, так как не смог найти UI для работы с компаниями.. 

Может быть у кого то это уже есть и просто забыли пушнуть? Или может мне переделать процесс запроса добавления пользователя под новый лад с использованием Companies::MembersController? И потом отдельным PR залить это и вернуться к email?

**Comment by kovalevsky** [comment]
@valexl добавлением пользователя в компанию на новый лад сейчас занимается @pplevako в рамках #81.
Я думаю, лучше подождать, пока мы смержем весь функционал. 

@pplevako, навскидку, какой объем работы остался по #81?

**Comment by valexl** [comment]
@kovalevsky ок. @pplevako если ты ее не начинал еще, могу я ей заняться..

**Comment by pplevako** [comment]
@valexl Добавление пользователя на новый лад сейчас находится в PR https://github.com/IT61/it61-rails/pull/85/files. Неплохо бы его смержить в companies2.
Тогда отправку писем можно добавить в `app/models/company/membership_request.rb#approve!` и `app/controllers/companies/membership_requests_controller.rb#create`.
Я обнаружил, что `Companies::MembersController#destroy` нерабочий — третье место для отправки почты. Могу исправить это прямо в companies2.

**Comment by valexl** [comment]
@pplevako значит тесты все таки не врали:) 

Я думаю можно его в твой PR добавить. И как его сольют сюда так сразу у меня и UI появится и баг уйдет...
